Create a table called orders that records: order_id, person_id, product_name, product_price, quantity.
-- CREATE TABLE orders(
--   id SERIAL PRIMARY KEY,
--   order_id INTEGER,
--   person_id INTEGER,
--   product_name VARCHAR(30), 
-- 	product_price FLOAT,
--   quantity INTEGER
--   );
  --# 2 Add 5 orders to the orders table.
--Make orders for at least two different people.
--person_id should be different for different people.
-- INSERT INTO orders(person_id, product_name, product_price, quantity)
-- 	values(1, 'bould', 100000, 4),
--   (2, 'jellyfish', 100000, 1),
--   (3, 'bould', 50000, 4),
--   (4, 'bould', 150000, 3),
--   (5, 'bould', 25000000, 1)
  --#3 Select all the records from the orders table.
--   SELECT * FROM orders 
  --#4 Calculate the total number of products ordered.
--   SELECT SUM (quantity) FROM orders
  --#5 Calculate the total order price.
--   select sum (product_price * 1) FROM orders
  --#6 Calculate the total order price by a single person_id.
  --SELECT SUM(product_price * quantity) FROM orders WHERE person_id = 1;
  